language: objective-c
osx_image: xcode9.4

cache: 
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds

script:
  - xcodebuild clean test
  - workspace ClaroChallenge.xcworkspace
  - scheme ClaroChallenge
  - destination "platform=iOS Simulator, name=iPhone 7, OS=10.4" ONLY_ACTIVE_ARCH=NO
  - quit
