language: objective-c
osx_image: xcode9.4

cache: 
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds

script:
  - xcodebuild -list
  - xcodebuild -project ClaroChallenge.xcodeproj -scheme "ClaroChallenge" clean build 
  - bundle exec pod install
  - xcodebuild -list
  - travis_retry xcodebuild -workspace ClaroChallenge.xcworkspace -scheme "ClaroChallenge" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=9.4' test
