language: objective-c
osx_image: xcode9.4
install: bundle install --gemfile Gemfile

cache: 
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds

script:
  - xcodebuild -version
  - xcodebuild -list
  - xcodebuild -project ClaroChallenge.xcodeproj clean build 
  - bundle install --deployment
  - bundle exec pod install
  - xcodebuild -list
  - travis_retry xcodebuild -workspace ClaroChallenge.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=9.4' test
